tp1/tp1_aspnet_mvc/Web/Controllers/FriendsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.ViewModel;
using Bussines;
using Web.Lib;

namespace Web.Controllers
{
    public class FriendsController : Controller
    {
        // GET: Friends
        public ActionResult Index()
        {
            List<Amigo> amigos = new List<Amigo>();
            amigos = Helper.ToViewModel(Rules.UsersList());
            return View(amigos);
        }

        public ActionResult WithBirthday()
        {
            List<Amigo> amigos = new List<Amigo>();
            amigos = Helper.ToViewModel(Rules.UsersList());
            return View(amigos);
        }

        public ActionResult WithEmail()
        {
            List<Amigo> amigos = new List<Amigo>();
            amigos = Helper.ToViewModel(Rules.UsersList());
            return View(amigos);
        }

        // POST: Friends/CreateCookie
        [HttpPost]
        public string CreateCookie(string value)
        {
            Rules.WriteCookie(value);
            return "_COOKEADO";
        }

        // POST: Friends/ReadCookie
        [HttpPost]
        public string ReadCookie()
        { 
            return Rules.ReadCookie("CookieIDs");
        }

        // GET: Friends/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Friends/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Friends/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Friends/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Friends/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Friends/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Friends/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

tp1/tp1_aspnet_mvc/Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

tp1/tp1_aspnet_mvc/Web/Views/Friends/CreateCookie.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CreateCookie</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

tp1/tp1_aspnet_mvc/Web/Views/Friends/Index.cshtml
@model IEnumerable<Web.ViewModel.Amigo>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PessoaID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sobrenome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DtAniversario)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <input type="checkbox" value="" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PessoaID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sobrenome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DtAniversario)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

tp1/tp1_aspnet_mvc/Web/Views/Friends/WithBirthday.cshtml
@model IEnumerable<Web.ViewModel.Amigo>

@{
    ViewBag.Title = "WithBirthday";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>WithBirthday</h2>
<p>@Html.ActionLink("Lista de amigos com Email", "WithEmail", "Friends")</p>

<!--<p>
    @Html.ActionLink("Create New", "Create")
</p>-->
<table class="table">
    <tr>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.PessoaID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sobrenome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DtAniversario)
        </th>
        <!-- <th></th>-->
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <input type="checkbox" value="@Html.DisplayFor(modelItem => item.PessoaID)" data-nome="@Html.DisplayFor(modelItem => item.Nome)" id="checkbox_@Html.DisplayFor(modelItem => item.PessoaID)" name="checkbox" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PessoaID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sobrenome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DtAniversario)
            </td>
            <!--<td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>-->
        </tr>
    }

</table>

tp1/tp1_aspnet_mvc/Web/Views/Friends/WithEmail.cshtml
@model IEnumerable<Web.ViewModel.Amigo>

@{
    ViewBag.Title = "WithEmail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>WithEmail</h2>
<p>@Html.ActionLink("Lista de amigos com aniversário", "WithBirthday", "Friends")</p>

<!--<p>
    @Html.ActionLink("Create New", "Create")
</p>-->
<table class="table">
    <tr>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.PessoaID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sobrenome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <!--<th></th>-->
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <input type="checkbox" value="@Html.DisplayFor(modelItem => item.PessoaID)" data-nome="@Html.DisplayFor(modelItem => item.Nome)" id="checkbox_@Html.DisplayFor(modelItem => item.PessoaID)" name="checkbox" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PessoaID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sobrenome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <!--
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
            -->
        </tr>
    }

</table>

tp1/tp1_aspnet_mvc/Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nome do aplicativo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>@Html.ActionLink("Sobre", "About", "Home")</li>
                    <li>@Html.ActionLink("Contato", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meu Aplicativo ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/main.js"></script>
</body>
</html>